server:
  port: 9001
#  tomcat:
#    uri-encoding: utf-8
#    max-threads: 1000
#    max-connections: 10000
#  basedir: /tmp/tomcat

spring:
  datasource:
    name: textbook
    url: jdbc:mysql:///textbook?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456

#mybatis官网要求配置方式
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
mapper:
  mappers: com.example.studentBackend.common.mybatis.CommonMapper
  # 安全删除，不允许删全表
  safe-delete: true
  safe-update: true

#生成token的配置信息
jwt:
  secret: xx1WET12^%3^(WE45
  expiration: 36000  # Token expiration time in seconds (e.g., 1 hour)